apiVersion: v1 # Especifica a versão da API do Kubernetes para o objeto Service.
kind: Service # Define o tipo de objeto Kubernetes como um Service.
metadata: # Contém metadados sobre o Service.
  name: backend-service # O nome do Service.
spec: # Define o estado desejado do Service.
  selector: # Define como o Service encontra os Pods para os quais ele roteará o tráfego.
    app: backend # Roteia o tráfego para Pods com o label `app: backend`. Isso deve corresponder aos labels dos Pods criados pelo Deployment do backend.
  ports: # Define as portas do Service.
    - protocol: TCP # O protocolo da porta.
      port: 3000 # A porta na qual o Service estará escutando. Por padrão, para um Service do tipo ClusterIP (implícito aqui, pois `type` não está definido), esta porta é interna ao cluster.
      targetPort: 3000 # A porta nos Pods do backend para a qual o tráfego será encaminhado. Deve corresponder à `containerPort` definida no Deployment do backend.